artifacts_root: artifacts

data ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/soudeep-cse/ETE_Ml_project/raw/refs/heads/main/winequality-red.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/winequality-red.csv

model_trainer:
  root_dir: artifacts/data_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
